language: julia
os:
  - osx
  - linux
julia:
  - release
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
    - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("ProjectiveDictionaryPairLearning"))`)'
    - julia -e 'Pkg.pin("ProjectiveDictionaryPairLearning"); Pkg.resolve()'
    - julia -e 'Pkg.clone("NumericExtensions")'
    - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia --check-bounds=yes --inline=no --code-coverage=user -e 'Pkg.test("ProjectiveDictionaryPairLearning")'; fi
    - if [ $TRAVIS_JULIA_VERSION = "release" ]; then julia --check-bounds=yes -e 'Pkg.test("ProjectiveDictionaryPairLearning")'; fi
after_success:
    - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'cd(Pkg.dir("ProjectiveDictionaryPairLearning")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
