language: julia
os:
  - osx
  - linux
julia:
  - release
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
    - julia -e 'Pkg.add("ProjectiveDictionaryPairLearning"); Pkg.checkout("ProjectiveDictionaryPairLearning")'
    - julia -e 'run(`ln -s $(pwd()) $(Pkg.dir("ProjectiveDictionaryPairLearning"))`); Pkg.pin("ProjectiveDictionaryPairLearning"); Pkg.resolve()'
    - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia --check-bounds=yes --inline=no --code-coverage=user -e test/runtests.jl; fi
    - if [ $TRAVIS_JULIA_VERSION = "release" ]; then julia --check-bounds=yes -e test/runtests.jl; fi
after_success:
    - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'cd(Pkg.dir("ProjectiveDictionaryPairLearning")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
